
version: '2'
services:
    hub:
        image: selenium/hub:3.141.59-mercury
        ports:
            - "4444:4444"

    firefox:
        image: selenium/node-firefox-debug:3.141.59-mercury
        volumes:
            - /dev/shm:/dev/shm
            - /home/julien/test:/home/selenium/upload
        depends_on:
            - hub
        environment:
            HUB_HOST: hub
        ports:
            - 5900

    chrome:
        image: selenium/node-chrome-debug:3.141.59-mercury
        volumes:
            - /dev/shm:/dev/shm
            - /home/julien/test:/home/selenium/upload
        depends_on:
            - hub
        environment:
            HUB_HOST: hub
        ports:
            - 5900

    docker-gen:
        image: jwilder/docker-gen
        command: -watch /etc/docker-gen/templates/vnc.tmpl /usr/share/nginx/html/index.html
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./vnc.tmpl:/etc/docker-gen/templates/vnc.tmpl
    nginx:
        image: nginx
        depends_on:
            - hub
        ports:
            - "4445:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - /usr/share/nginx/html/
            - ./assets:/usr/share/nginx/html/assets/
